import  { type Question } from '@/lib/types'

export const BASIC_MATCHING_QUESTIONS: Question[] = [
  {
    id: 'q1',
    category: 'welfare',
    text: '今いちばん不安に感じていることは？',
    type: 'choice',
    options: ['子育て・教育', '医療・介護', '災害・防災', '物価・生活費', '老後の生活', 'その他'],
    order: 1,
  },
  {
    id: 'q2',
    category: 'economy',
    text: '国と自治体、どちらにより期待しますか？',
    type: 'choice',
    options: ['国に期待する', '自治体に期待する', '両方に期待する', 'どちらも期待しない'],
    order: 2,
  },
  {
    id: 'q3',
    category: 'welfare',
    text: '安心と自由、どちらを重視しますか？',
    type: 'choice',
    options: ['安心を重視', '自由を重視'],
    order: 3,
  },
  {
    id: 'q4',
    category: 'education',
    text: '子どもの教育について、どのように考えていますか？',
    type: 'choice',
    options: [
      'より良い教育環境の整備を優先',
      '教育費の負担軽減を優先',
      '多様な教育の選択肢を増やす',
      '特に考えていない',
    ],
    order: 4,
  },
  {
    id: 'q5',
    category: 'economy',
    text: '経済政策で重視するのは？',
    type: 'choice',
    options: ['成長重視', '分配重視', 'バランス重視', '分からない'],
    order: 5,
  },
  {
    id: 'q6',
    category: 'environment',
    text: '環境問題への取り組みについて',
    type: 'choice',
    options: ['積極的に取り組むべき', '経済を優先すべき'],
    order: 6,
  },
  {
    id: 'q7',
    category: 'local',
    text: '地域の課題で気になることは？',
    type: 'choice',
    options: [
      '公共交通の維持・充実',
      '商業施設・商店街の活性化',
      '災害対策・防災',
      '高齢者支援',
      '子育て支援',
      '特にない',
    ],
    order: 7,
  },
  {
    id: 'q8',
    category: 'welfare',
    text: '社会保障について',
    type: 'choice',
    options: ['拡充すべき', '削減すべき'],
    order: 8,
  },
]

// 詳細投票マッチング質問（30-50問規模）
export const DETAILED_MATCHING_QUESTIONS: Question[] = [
  ...BASIC_MATCHING_QUESTIONS,
  {
    id: 'q9',
    category: 'constitution',
    text: '憲法改正について',
    type: 'scale',
    options: ['賛成', '', '', '', '反対'],
    order: 9,
  },
  {
    id: 'q10',
    category: 'diplomacy',
    text: '外交政策で重視するのは？',
    type: 'choice',
    options: ['日米関係', 'アジア諸国との関係', '多国間協調', '特に考えていない'],
    order: 10,
  },
  {
    id: 'q11',
    category: 'economy',
    text: '消費税について',
    type: 'scale',
    options: ['増税すべき', '', '', '', '減税すべき'],
    order: 11,
  },
  {
    id: 'q12',
    category: 'education',
    text: '大学無償化について',
    type: 'scale',
    options: ['賛成', '', '', '', '反対'],
    order: 12,
  },
  {
    id: 'q13',
    category: 'welfare',
    text: '年金制度改革について',
    type: 'choice',
    options: [
      '給付水準を維持すべき',
      '負担を増やすべき',
      '抜本的な見直しが必要',
      '分からない',
    ],
    order: 13,
  },
  {
    id: 'q14',
    category: 'environment',
    text: '脱炭素社会の実現について',
    type: 'scale',
    options: ['積極的に推進すべき', '', '', '', '慎重に進めるべき'],
    order: 14,
  },
  {
    id: 'q15',
    category: 'economy',
    text: '最低賃金の引き上げについて',
    type: 'scale',
    options: ['積極的に引き上げるべき', '', '', '', '慎重にすべき'],
    order: 15,
  },
]

