export const PREFECTURES: Array<{ code: string; name: string; nameKana: string }> = [
  { code: '01', name: '北海道', nameKana: 'ホッカイドウ' },
  { code: '02', name: '青森県', nameKana: 'アオモリケン' },
  { code: '03', name: '岩手県', nameKana: 'イワテケン' },
  { code: '04', name: '宮城県', nameKana: 'ミヤギケン' },
  { code: '05', name: '秋田県', nameKana: 'アキタケン' },
  { code: '06', name: '山形県', nameKana: 'ヤマガタケン' },
  { code: '07', name: '福島県', nameKana: 'フクシマケン' },
  { code: '08', name: '茨城県', nameKana: 'イバラキケン' },
  { code: '09', name: '栃木県', nameKana: 'トチギケン' },
  { code: '10', name: '群馬県', nameKana: 'グンマケン' },
  { code: '11', name: '埼玉県', nameKana: 'サイタマケン' },
  { code: '12', name: '千葉県', nameKana: 'チバケン' },
  { code: '13', name: '東京都', nameKana: 'トウキョウト' },
  { code: '14', name: '神奈川県', nameKana: 'カナガワケン' },
  { code: '15', name: '新潟県', nameKana: 'ニイガタケン' },
  { code: '16', name: '富山県', nameKana: 'トヤマケン' },
  { code: '17', name: '石川県', nameKana: 'イシカワケン' },
  { code: '18', name: '福井県', nameKana: 'フクイケン' },
  { code: '19', name: '山梨県', nameKana: 'ヤマナシケン' },
  { code: '20', name: '長野県', nameKana: 'ナガノケン' },
  { code: '21', name: '岐阜県', nameKana: 'ギフケン' },
  { code: '22', name: '静岡県', nameKana: 'シズオカケン' },
  { code: '23', name: '愛知県', nameKana: 'アイチケン' },
  { code: '24', name: '三重県', nameKana: 'ミエケン' },
  { code: '25', name: '滋賀県', nameKana: 'シガケン' },
  { code: '26', name: '京都府', nameKana: 'キョウトフ' },
  { code: '27', name: '大阪府', nameKana: 'オオサカフ' },
  { code: '28', name: '兵庫県', nameKana: 'ヒョウゴケン' },
  { code: '29', name: '奈良県', nameKana: 'ナラケン' },
  { code: '30', name: '和歌山県', nameKana: 'ワカヤマケン' },
  { code: '31', name: '鳥取県', nameKana: 'トットリケン' },
  { code: '32', name: '島根県', nameKana: 'シマネケン' },
  { code: '33', name: '岡山県', nameKana: 'オカヤマケン' },
  { code: '34', name: '広島県', nameKana: 'ヒロシマケン' },
  { code: '35', name: '山口県', nameKana: 'ヤマグチケン' },
  { code: '36', name: '徳島県', nameKana: 'トクシマケン' },
  { code: '37', name: '香川県', nameKana: 'カガワケン' },
  { code: '38', name: '愛媛県', nameKana: 'エヒメケン' },
  { code: '39', name: '高知県', nameKana: 'コウチケン' },
  { code: '40', name: '福岡県', nameKana: 'フクオカケン' },
  { code: '41', name: '佐賀県', nameKana: 'サガケン' },
  { code: '42', name: '長崎県', nameKana: 'ナガサキケン' },
  { code: '43', name: '熊本県', nameKana: 'クマモトケン' },
  { code: '44', name: '大分県', nameKana: 'オオイタケン' },
  { code: '45', name: '宮崎県', nameKana: 'ミヤザキケン' },
  { code: '46', name: '鹿児島県', nameKana: 'カゴシマケン' },
  { code: '47', name: '沖縄県', nameKana: 'オキナワケン' },
]

export const PREFECTURE_MAP = new Map(
  PREFECTURES.map((pref) => [pref.code, pref])
)

